2019-03-16 14:05:35,763 - root - ERROR - put请求出错，出错原因:HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /todos/todo1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003CBD978>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2019-03-16 14:05:35,767 - root - INFO - 请求传入数据：url:http://127.0.0.1:5000/todos/todo1,key:16.0,参数:{"task":"put success"},请求方式：PUT
2019-03-16 14:05:35,769 - root - INFO - 测试用例执行完毕
2019-03-16 14:05:35,774 - root - INFO - ----------------------------------
2019-03-16 14:05:35,777 - root - INFO - 测试用例开始执行
2019-03-16 14:05:35,780 - root - INFO - 获取用例数据:{'expect2': 'task=update success', 'name': 'put请求返回resultcode和task正确', 'id': 5.0, 'url': 'http://127.0.0.1:5000/todos/todo2', 'key': 17.0, 'expect1': 'code=201', 'param': '{"task":"update success"}', 'place': 'database', 'way': 'PUT'}
2019-03-16 14:05:35,799 - root - INFO - 当前接口涉及数据库：orderdb
2019-03-16 14:05:35,871 - root - INFO - 成功登录数据库：orderdb，版本为：8.0.11，执行SQL：select content from blog_blog where id = '7'
2019-03-16 14:05:35,884 - root - INFO - 查询结果：{"task":"update success"}
2019-03-16 14:05:35,886 - root - INFO - 数据格式为：{"task":"update success"}
