2019-03-16 14:05:30,651 - root - ERROR - put请求出错，出错原因:HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /todos/todo2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000003CD8CC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2019-03-16 14:05:30,654 - root - INFO - 请求传入数据：url:http://127.0.0.1:5000/todos/todo2,key:11.0,参数:{"task":"update success"},请求方式：PUT
2019-03-16 14:05:30,657 - root - INFO - 测试用例执行完毕
2019-03-16 14:05:30,659 - root - INFO - ----------------------------------
2019-03-16 14:05:30,663 - root - INFO - 测试用例开始执行
2019-03-16 14:05:30,666 - root - INFO - 获取用例数据:{'expect2': 'param=null', 'name': 'delete请求成功删除数据', 'id': 6.0, 'url': 'http://127.0.0.1:5000/todos/todo1', 'key': 12.0, 'expect1': 'code=204', 'param': 'not argument', 'place': '', 'way': 'DELETE'}
